# Generated by Django 4.1 on 2022-08-19 08:00

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webpage', '0002_delete_usercourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
