# Generated by Django 4.1 on 2022-08-19 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='video',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='slug',
        ),
        migrations.AddField(
            model_name='youtube',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
